<?php
if($action == "test") {
	/*$send_mail = new SendMail();
	$subject = "Test Mail From Ispatindo Web Service";
	$body = "<html>"
						. "<head>"
						. "<style>"
						. "body {font-family: 'Calibri', arial, sans-serif;}"
						. "pre {font-family: 'Calibri', arial, sans-serif;}"
						. "</head>"
						. "<body>";
		$body .= "<p><i>This email is automatically generated by system, please do not reply.</i></p>";
		$body .= "</body>"
					. "</html>";
	$recipient[0] = "dheo.pratama@ispatindo.com";
	$send_mail->sendTheMail($subject, $body, $recipient);*/
  $numc = 10;
	$numc = str_pad($numc, 10, '0', STR_PAD_LEFT);
	echo $numc;
}
?>