<?php
require '../classes/SendMail.php';

$send_mail = new SendMail();
$subject = "Test Mail From Ispatindo Web Service";
$body = "<html>"
          . "<head>"
          . "<style>"
          . "body {font-family: 'Calibri', arial, sans-serif;}"
          . "pre {font-family: 'Calibri', arial, sans-serif;}"
          . "</head>"
          . "<body>";
  $body .= "<p><i>This email is automatically generated by system, please do not reply.</i></p>";
  $body .= "</body>"
        . "</html>";
$recipient[0] = "dheo.pratama@ispatindo.com";
$send_mail->sendTheMail($subject, $body, $recipient);
?>